modLoader = "javafml" #mandatory
loaderVersion = "[0,)"# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
license = "${mod_license}"
[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${mod_version}" #mandatory
displayName = "${mod_name}" #mandatory
#updateJSONURL = "https://api.modrinth.com/updates/create-mechanical-spawner/forge_updates.json"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="logo.png" #optional
# A text field displayed in the mod UI
credits="Thanks to the Creators of Create" #optional
# A text field displayed in the mod UI
authors = "${mod_author}" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Create Addon with mob spawning mechanics.
'''

[[dependencies."${mod_id}"]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId = "create"
mandatory = true
versionRange="[6.0.4,6.1.0)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "mechanicals"
mandatory = true
versionRange="[1.0.3,1.1.0)"
ordering = "AFTER"
side = "BOTH"